version: '3.4'
services:
  sugarcrm:
    build: .
    depends_on: [db]
    ports:
      - "2080:80"
    links:
      - "db"
    environment:
      DB_TYPE: mysql
      DB_MANAGER: MysqlManager
  db:
    image: mysql:5.7
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: blablabla
      MYSQL_DATABASE: sugarcrm
      MYSQL_USER: sugarcrm
      MYSQL_PASSWORD: blablabla
